# Generated by Django 4.2.30 on 2026-10-06 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del plan')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('duracion_semanas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Duración (semanas)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio mensual')),
                ('cupos_disponibles', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Cupos disponibles')),
                ('entrenador', models.CharField(max_length=80, verbose_name='Entrenador a cargo')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de Entrenamiento',
                'verbose_name_plural': 'Planes de Entrenamiento',
                'ordering': ['-creado_en'],
            },
        ),
    ]
